### ISSUE TITLE
PyPI source tar.gz fails to build

### ISSUE THREAD

**Issue by cirla** [cirla/tulipy#12]
Installing from wheel works fine, but installing via the source tar.gz (via `pip install tulipy`) fails.

1. Dependencies must not be correctly specified, as it throws errors during setup about `numpy` or `Cython` missing instead of installing them before attempting setup.
2. Contents of `libindicators` directory is not included in the package, as compilation failes (e.g. `fatal error: 'indicators.h' file not found`).

**Comment by codeplea** [comment]
Regarding point 2, it appears that the `libindicators` directory is included, however it is missing only the `indicators.h` file.
