### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by codeplea** [cirla/tulipy#16]
Hi Tim,

Right now the Github project description is `Python bindings for https://github.com/TulipCharts/tulipindicators`.

I was thinking that if the description was changed to contain some keywords, that it might help people find the project through search. Perhaps it could be `Tulipy - Financial Technical Analysis Indicator Library` or something like that. As it is now, a search for [technical analysis tulipy](https://github.com/search?utf8=%E2%9C%93&q=tulipy+technical+analysis&type=) doesn't even hit.

**Comment by cirla** [comment]
Sorry for the late reply, I was losing notifications for this repo to overly aggressive email filtering. I updated the GitHub project description and I'll close this issue after updating some metadata on PyPI.
