### ISSUE TITLE
Various Thoughts

### ISSUE THREAD

**Issue by codeplea** [cirla/tulipy#2]
I tried out the bindings today. Seems to work well.

I'm pretty excited to see this, since I was planning on doing Python bindings
anyway. I know that a lot of people in the finance industry use Python.

Some thoughts:

1) You may want to consider adding `tiamalgamation.c` and `indicators.h` to
your repo. That way users don't have to download Tulip Indicators separately to
build it. You can build it with "make tiamalgamation.c", or if you have trouble
you can get it from my node.js bindings repo.

2) You should probably expose TI_VERSION.

3) I think the error handling should be a bit more robust. Indicators may
return TI_INVALID_OPTION if given bad options. Since users often supply the
option values, this can happen a lot. I don't know the best way to handle it
though.

4) I don't think there is a need to set the last input and output array to NULL.

5) There should probably be some checking that all inputs are the same length.
Right now, I suspect you can segfault it with this.  Ideally,
you should find the shortest length input array, and then trim all the longer input
arrays to match (discarding data from the left of the array - that is so the
last bar lines up - very useful if you're running an indicator on outputs of
other indicators that produce different lengths). This is what I did in the
node.js bindings.

If you like, I can work all that up into a pull request, but I don't want to
step on your toes. Let me know what you want me to do.

Anyway, I think you have a really good start! I wanted to do a Python binding,
so this saves me a lot of work.

**Comment by cirla** [comment]
All great points! I was just excited to throw up a repo as soon as I got code that compiled and was usable, but I had definitely intended to make it more robust and handle all of the above before submitting to [PyPI](https://pypi.python.org/pypi).

In addition to the above, I wanted to clean up a few other things bothering me:

1. [This `ti_find_indicator` call](https://github.com/cirla/tulipy/blob/0630f34208d3a3b9dd3914e2e86b9948c82013a0/src/tulipy.pyx#L22) is completely unnecessary seeing as we already have the indicator info [here](https://github.com/cirla/tulipy/blob/0630f34208d3a3b9dd3914e2e86b9948c82013a0/src/tulipy.pyx#L85), but [the __cinit__ function seems to insist that all of its arguments must be Python objects](https://mail.python.org/pipermail/cython-devel/2012-June/002734.html) and it complained whenever I tried something like:
  ```python
  def __cinit__(self, const ti.ti_indicator_info * info):
  ```
2. I have to take a closer look at the generated C, but I'm not sure if [this assignment](https://github.com/cirla/tulipy/blob/0630f34208d3a3b9dd3914e2e86b9948c82013a0/src/tulipy.pyx#L65) makes an unnecessary copy of each input, but Cython needed [this declaration](https://github.com/cirla/tulipy/blob/0630f34208d3a3b9dd3914e2e86b9948c82013a0/src/tulipy.pyx#L61) to let me [take the address](https://github.com/cirla/tulipy/blob/0630f34208d3a3b9dd3914e2e86b9948c82013a0/src/tulipy.pyx#L66) as the `inputs` param is a Python object.
3. I haven't done any kind of analysis to see whether or not any of this leaks memory.

**Comment by cirla** [comment]
PRs are always welcome, of course. I've added you as a collaborator so that you can approve them as well.

**Comment by cirla** [comment]
I think I mostly addressed all of your points in #4 and a few direct pushes to `master` (a bad habit I need to stop). Let me know what you think.

**Comment by codeplea** [comment]
>This ti_find_indicator call is completely unnecessary...

I think we can do it by passing the index instead. See [here](https://github.com/cirla/tulipy/pull/5).

By the way, you are making GREAT progress! I was really surprised to see all you've done since I last checked. Good work.
