### ISSUE TITLE
feed data to calculate stochrsi

### ISSUE THREAD

**Issue by CnsAd** [cirla/tulipy#26]
I use the below code to calculate the stochrsi:
```
klines = bot.client.get_klines(symbol=coin, interval=intv)
    array = np.array(klines, dtype='f8')
    df = pd.DataFrame(data=array[:, 0:6], columns=["date", "open", "high", "low", "close", "volume"])
    fastd, fastk = ti.stochrsi(np.array(df['close'].values), 14)
```
But I receive an Error: ValueError: too many values to unpack (expected 2)
What's wrong?

**Comment by CnsAd** [comment]
I noticed that it calculates only ONE output as StochRSI. What if I want to have fastd and fastk as usual StochRSI like what we see in any exchanges or tradingview.com?

**Comment by codeplea** [comment]
Are you sure you want [StochRSI](https://tulipindicators.org/stochrsi)? It sounds like you just want [Stoch](https://tulipindicators.org/stoch).

**Comment by CnsAd** [comment]
I used `ti.stochrsi` and I want Stoch RSI

**Comment by CnsAd** [comment]
![image](https://user-images.githubusercontent.com/17598472/55122063-087eb800-511b-11e9-93e4-baeafda0baad.png)

**Comment by codeplea** [comment]
Ok, so Tulip Indicators implements StochRSI as originally described in Stocks & Commodities V. 11:05: Stochastic RSI And Dynamic Momentum Index by Tushar Chande and Stanley Kroll.

It sounds like what you want, is to apply Stoch to RSI, which is actually also pretty common. Currently TI won't do this, but it will likely be added in the near future. More info here: https://github.com/TulipCharts/tulipindicators/issues/23

Anyway, I think you can run RSI and then run STOCH on the result to obtain what you're looking for.

**Comment by CnsAd** [comment]
TY
