### ISSUE TITLE
Can't install tulipy in Debian

### ISSUE THREAD

**Issue by xuanngo2001** [cirla/tulipy#27]
I ran
```
pip3 install tulipy
```
It gives the following errors:
```
                       ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nzh81hjq/tulipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wkq0j4eo-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-nzh81hjq/tulipy/
```

I have the following packages installed in my system:
```
>pip3 show numpy Cython wheel
Name: numpy
Version: 1.16.2
---
Name: Cython
Version: 0.29.6
---
Name: wheel
Version: 0.33.1
```

**Comment by codeplea** [comment]
Try this: `sudo apt-get install build-essential`

**Comment by codeplea** [comment]
[Tulip Indicators](https://github.com/tulipcharts/tulipindicators) is programmed in C, so you have to be able to compile it. You could always compile it on a separate machine and then copy it over. Alternatively, I think you can probably uninstall python3-dev after installing tulipy.

Why are you running on RAM?

**Comment by xuanngo2001** [comment]
I run my OS in RAM because I pack all apps that I need into an ISO and boot it through USB.

By the way, thx for your effort in creating Tulip Indicators library.
