### ISSUE TITLE
SSMA - smoothed simple moving average

### ISSUE THREAD

**Issue by rrfaria** [cirla/tulipy#28]
Hi,

first of all thank you for your amazing job.

I would like to ask you if do you know how to calculate ssma?

I saw this indicator on iqoption site but I can't found how to calc this.

I found SMA but not SSMA.

could you help me ?

**Comment by cirla** [comment]
[Tulip Indicators](https://github.com/TulipCharts/tulipindicators) does not provide SMMA and this is just a wrapper around that library. You could use the Exponential Moving Average (`tulipy.ema`) and double the `period` parameter to approximate a Smoothed Moving Average.
