### ISSUE TITLE
PEP 517 Error during Installation of Tulipy

### ISSUE THREAD

**Issue by donchew** [cirla/tulipy#34]
I come to understand that Tulipy does not support Python < 3.5 on Windows. I am using Python 2.7.

However, I have then installed Python 3.6 on Win 10 but still face the issue of the of the following.

> Collecting tulipy
  Using cached https://files.pythonhosted.org/packages/2c/fc/685a3fe73a66ed35332058c2e22b2ed63b7725ec32817753f11c06f48792/tulipy-0.4.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in c:\python36\lib\site-packages (from tulipy) (1.16.2)
Building wheels for collected packages: tulipy
  Building wheel for tulipy (PEP 517) ... error
  Complete output from command c:\python36\python.exe c:\python36\lib\site-packages\pip\_vendor\pep517\_in_process.py build_wheel C:\Users\DONCHE~1\AppData\Local\Temp\tmpr1_u_tov:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\tulipy
  copying tulipy\__init__.py -> build\lib.win-amd64-3.6\tulipy
  running build_ext
  skipping 'tulipy/lib\__init__.c' Cython extension (up-to-date)
  building 'tulipy.lib' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\libindicators
  creating build\temp.win-amd64-3.6\Release\tulipy
  creating build\temp.win-amd64-3.6\Release\tulipy\lib
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ilibindicators -Itulipy/lib -IC:\Users\DONCHE~1\AppData\Local\Temp\pip-build-env-80wtphaq\overlay\Lib\site-packages\numpy\core\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" /Tclibindicators/tiamalgamation.c /Fobuild\temp.win-amd64-3.6\Release\libindicators/tiamalgamation.obj
  tiamalgamation.c
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ilibindicators -Itulipy/lib -IC:\Users\DONCHE~1\AppData\Local\Temp\pip-build-env-80wtphaq\overlay\Lib\site-packages\numpy\core\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" /Tctulipy/lib\__init__.c /Fobuild\temp.win-amd64-3.6\Release\tulipy/lib\__init__.obj
  __init__.c
  c:\users\don chew\appdata\local\temp\pip-build-env-80wtphaq\overlay\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\python36\libs /LIBPATH:c:\python36\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64" /EXPORT:PyInit_lib build\temp.win-amd64-3.6\Release\libindicators/tiamalgamation.obj build\temp.win-amd64-3.6\Release\tulipy/lib\__init__.obj /OUT:build\lib.win-amd64-3.6\tulipy\lib.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\libindicators\lib.cp36-win_amd64.lib
  __init__.obj : warning LNK4197: export 'PyInit_lib' specified multiple times; using first specification
     Creating library build\temp.win-amd64-3.6\Release\libindicators\lib.cp36-win_amd64.lib and object build\temp.win-amd64-3.6\Release\libindicators\lib.cp36-win_amd64.exp
  Generating code
  Finished generating code
  LINK : fatal error LNK1158: cannot run 'rc.exe'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158

  ----------------------------------------
  **Failed building wheel for tulipy**
  Running setup.py clean for tulipy
Failed to build tulipy
**Could not build wheels for tulipy which use PEP 517 and cannot be installed directly**
>

**Comment by cirla** [comment]
This is an issue with Visual Studio, not tulipy. See [this comment](https://github.com/conan-io/conan/issues/1340#issuecomment-327950375).

**Comment by cirla** [comment]
Also, I am working on supporting Python 2.7 on Windows. I may be able to get it working by switching to cffi instead of Cython and building the CPython extension independently of the C library.

**Comment by havocesp** [comment]
I get a very very similar error when upgrading to 0.4.0 in Debian and finally I solve it by adding `--no-clean` argument to `pip install`, just try it,  ... :-)

Regards

**Comment by azidyn** [comment]
^ above didn't work for me on Ubuntu but this did:

`pip3 install tulipy --global-option="build"`

warning: takes ~20-40 minutes

**Comment by jwaresolutions** [comment]
I had this same issue when attempting to install tulipy with python3.9. It works great on Python 3.8.5
 though.
