### ISSUE TITLE
Please help with examples as go-bys

### ISSUE THREAD

**Issue by dreamerx88** [cirla/tulipy#39]
Please help newcomers with examples on how to call indicators and specific outputs when the indicators have multiple output arrays. Would very much appreciate examples with macd, stoch and crossover indicators. Thanks!

ps. have been able to duplicate usage example in https://tulipindicators.org/usage however it doesn't go through how to manipulate output arrays of BB...for example taking action on output array of BB High with the crossover indicator..not sure how to do that..

**Comment by codeplea** [comment]
Do you want to post what you've tried so far?

**Comment by dreamerx88** [comment]
Sure. I went through line by line in the usage example provided and got the same output shown. Then I tried calling macd, it worked, same with macd[-1] but the output arrays of macd show all three output arrays - I dont know how to grab a specific output array, such as the macd line or the macd_signal and use with the crossover indicator -- need help on how to identify and pass the arrays to the crossover indicator. Here are the lines I added to the usage example:

DATA3 = np.array([100.65, 102.21, 103.54, ....])
macd = (ti.macd(DATA3, 12, 26, 9))
print(macd, macd[-1])

and the output of macd shows the three output arrays macd, macd_signal and macd_histogram

**Comment by cirla** [comment]
From the [README](https://github.com/cirla/tulipy/blob/master/README.md):

> Single outputs are returned directly. Indicators returning multiple outputs use a tuple in the order indicated by the outputs property.

You could put them in a dictionary if you wanted to refer to them by name, e.g.:

```python
results = dict(zip(ti.macd.outputs, ti.macd(DATA3, 12, 26, 9)))
print(results["macd_signal"])
```

**Comment by cirla** [comment]
Closing in favor of #40, please request anything else you'd like to see in the documentation there.
